services:
  - type: web
    name: cursos-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: "npm install"
    startCommand: "npm start"
    autoDeploy: true

  - type: web
    name: cursos-frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: "npm install && npm run build"
    staticPublishPath: "dist"
    autoDeploy: true
